---
-
  name: "NAMED: Install bind"
  yum:
    pkg: "{{ bind_package }}-{{ bind_version }}"
    state: present
    allow_downgrade: true
    lock_timeout: 5
  notify: "restart named"
  become: true
  when: ansible_os_family == 'RedHat'
  tags: [ "named", "install" ]
-
  name: "NAMED: create rsyslog socket for chroot"
  copy:
    dest: "/etc/rsyslog.d/named_chroot_socket.conf"
    content: "$AddUnixListenSocket /var/named/chroot/dev/log"
    owner: "root"
    group: "root"
    mode: "0644"
  notify: "restart rsyslog"
  become: true
  tags: [ "named", "config", "rsyslog" ]
-
  name: "NAMED: create named.conf"
  template:
    src: named.conf.j2
    dest: "{{ named_sysconfig_dir }}/named.conf"
    owner: "root"
    group: "{{ named_group }}"
    mode: "0640"
  notify: "restart named"
  become: true
  tags: [ "named", "config" ]
-
  name: "NAMED: create includes for named.conf"
  template:
    src: "{{ item }}.j2"
    dest: "{{ named_sysconfig_dir }}/named/{{ item }}"
    owner: "root"
    group: "{{ named_group }}"
    mode: "0640"
  with_items:
    - master.conf
    - slave.conf
  notify: "reload named"
  become: true
  tags: [ "named", "config", "zones" ]
-
  name: "NAMED: create masters directory for zone files"
  file:
    path: "{{ named_master_dst }}"
    owner: "root"
    group: "{{ named_group }}"
    mode: "0750"
    state: directory
  become: true
  tags: [ "named", "config", "zones" ]
-
  name: "NAMED: create slaves directory for zone files"
  file:
    path: "{{ named_slave_dst }}"
    owner: "{{ named_user }}"
    group: "{{ named_group }}"
    mode: "0750"
    state: directory
  become: true
  tags: [ "named", "config", "zones" ]
-
  name: "NAMED: copy master zone files"
  copy:
    src: "{{ item.src }}"
    dest: "{{ named_master_dst }}/{{ item.name }}"
    owner: "root"
    group: "{{ named_group }}"
    mode: "0640"
  with_items: "{{ named_master_zones }}"
  notify: "reload named"
  become: true
  tags: [ "named", "config" ]
-
  name: "NAMED: service enable"
  service: name={{ named_service }} enabled=yes state=started
  become: true
  tags: [ "named", "service" ]
